### ISSUE TITLE
wfnames missing on ELPA

### ISSUE THREAD

**Issue by ooglyhLL** [thierryvolpiatto/wfnames#1]
Wfnames is a dependency of Helm (ELPA), but not available from there.

**Comment by thierryvolpiatto** [comment]
ooglyhLL ***@***.***> writes:

> Wfnames is a dependency of Helm (ELPA), but not available from there.

Helm and Wfnames are available on Melpa and NonGnu(Elpa), not Elpa.
So to install Helm (and other packages) use:

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")
                         ("nongnu"
                         . "https://elpa.nongnu.org/nongnu/")))

To have this loaded early, put such settings in ../emacs.d/early-init.el
file.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

-- 
Thierry

**Comment by ooglyhLL** [comment]
Ah, yes. Sorry. Could it be that a recent Helm with this relatively new dependency is on melpa-stable, but wfnames isn't? In any case I have solved this problem for me now.

**Comment by thierryvolpiatto** [comment]
ooglyhLL ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Ah, yes. Sorry. Could it be that a recent Helm with this relatively
> new dependency is on melpa-stable, but wfnames isn't?

Don't think so because there is a tag 1.1 and Melpa-stable uses it.
Though I should provide a new version 1.2 of Wfnames, will do this soon
and create a new helm version using 1.2 as dependency. 

> In any case I have solved this problem for me now.

Great.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

-- 
Thierry
